modLoader="javafml"
loaderVersion="[${forge_version},)"
issueTrackerURL="https://github.com/TheCBProject/ChickenChunks"
license="The MIT License (MIT)"

[[mods]]
	modId="chickenchunks"
	displayName="ChickenChunks"
	version="${version}"

	updateJSONURL="https://version-check.covers1624.net/check/?mod=ChickenChunks&mc=${mc_version}"
	displayURL="http://chickenbones.net/Pages/links.html"
	authors="ChickenBones, covers1624"
	description="Advanced ChunkLoading management"
[[dependencies.chickenchunks]]
	modId="forge"
	mandatory=true
	versionRange="[${forge_version},)"
	ordering="NONE"
	side="BOTH"
[[dependencies.chickenchunks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
[[dependencies.chickenchunks]]
    modId="codechickenlib"
    mandatory=true
    versionRange="${ccl_version_range}"
    ordering="NONE"
    side="BOTH"
